In [1]:
import numpy as np

**NUMPY INDEXING AND SLICING OF VECTORS**

In [4]:
arr =np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

**same as list 
syntax:  arr[index number]

In [6]:
arr[2]

np.int64(13)

📌 #Slicing allows selecting a range of elements from a list or array using:
    [start : end : step]

✅ **Rules**:
- start:   Starting index (default = 0)
- end:     Ending index (not included, default = len(array))
- step:    Step size (default = 1)

🧠 Tip:
- Negative step = reverse order

In [7]:
arr[1:5]

array([12, 13, 14, 15])

In [8]:
arr[:5]


array([11, 12, 13, 14, 15])

In [9]:
arr[1:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
arr[1:5:2]

array([12, 14])

**NUMPY INDEXING AND SLICING OF Matrix**

In [12]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

**Indexing Elements**
syntax:
1) arr[row_index, column_index] -----> elm at that row,coloumn
2) arr[ index]------> print the row only
3) arr[:,index]-------> print the colunm


In [13]:
arr[0]

array([1, 2, 3, 4, 5])

In [14]:
arr[3]

array([16, 17, 18, 19, 20])

In [17]:
arr[4]

array([21, 22, 23, 24, 25])

In [18]:
arr[2,3]

np.int64(14)

In [26]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [20]:
arr[5,4]

np.int64(30)

✂️**Slicing Syntax (Getting submatrix):**
arr[start_row:end_row, start_col:end_col]


In [22]:
arr[1:3,1:3]

array([[ 7,  8],
       [12, 13]])

In [25]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

**Boolean Indexing**
🧠 Boolean Indexing in NumPy
✅ What is Boolean Indexing?
Boolean indexing lets you filter elements in an array using True/False conditions.

Instead of giving index numbers, you give a condition, and NumPy returns all elements that match!

📌 Key Syntax:
array[condition]


In [38]:
arr=np.arange(11,21)
arr


In [29]:
bool_index=arr%2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [39]:
even_ar = arr[bool_index]
even_ar

array([12, 14, 16, 18, 20])