In [1]:
import numpy as np

# Array Operations

## Arithmetic Operations
NumPy allows element-wise operations directly on arrays, just like working with numbers — no loops needed!

### 🔹 Basic Operations:

| Operation      | Code           | Output                                |
| -------------- | -------------- | ------------------------------------- |
| Addition       | `arr1 + arr2`  | `[11 22 33]`                          |
| Subtraction    | `arr1 - arr2`  | `[9 18 27]`                           |
| Multiplication | `arr1 * arr2`  | `[10 40 90]`                          |
| Division       | `arr1 / arr2`  | `[10. 10. 10.]`                       |
| Floor Div      | `arr1 // arr2` | `[10 10 10]`                          |
| Modulus        | `arr1 % arr2`  | `[0 0 0]`                             |
| Power          | `arr1 ** arr2` | `[10^1 20^2 30^3]` → `[10 400 27000]` |


##📌 Scalar Operations (array with number):
arr1 + 5        # [15 25 35]
arr2 * 2        # [2 4 6]

🧠 Notes:
Operations are done element-wise

Arrays must be of the same shape (or broadcastable)

In [7]:
a1= np.array([1,2,3,4,5])
a2= np.array([6,7,8,9,10])

In [8]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [9]:
a1-a2

array([-5, -5, -5, -5, -5])

In [10]:
a1%a2

array([1, 2, 3, 4, 5])

In [12]:
a2**a1

array([     6,     49,    512,   6561, 100000])

In [14]:
a1 // a2

array([0, 0, 0, 0, 0])

# Broadcasting in NumPy
✅ **What is Broadcasting?**
Broadcasting allows NumPy to perform arithmetic operations on arrays of different shapes — without writing loops.

It automatically expands the smaller array to match the shape of the larger one (without copying data).

🔹 **Rules of Broadcasting:**
If arrays have different shapes, NumPy tries to match them from the trailing dimensions.

If dimensions are not equal, one of them must be 1, so it can be stretched.

In [18]:
l=[10,20,30,40]
arr = np.array(l)
arr

array([10, 20, 30, 40])

In [19]:
arr + 10

array([20, 30, 40, 50])

In [22]:
arr2=np.arange(1,26).reshape(5,5)
arr2 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [21]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [24]:
arr2*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

# Deep And Shallow Copy

🧬 Deep Copy vs Shallow Copy in NumPy
When copying arrays, it's important to understand whether you're creating a real copy (new memory) or just another reference to the same data.
🔹 1. Shallow Copy (view() or direct assignment)
✅ What it does:
Creates a new variable that refers to the same data.

Changes in one array will reflect in the other.

🔹 2. Deep Copy (copy())
✅ What it does:
Creates a completely new array in memory.

Changes in one won’t affect the other.


| Type         | Method           | Memory Shared? | Changes Affect Original? |
| ------------ | ---------------- | -------------- | ------------------------ |
| Shallow Copy | `=` or `.view()` | ✅ Yes          | ✅ Yes                    |
| Deep Copy    | `.copy()`        | ❌ No           | ❌ No                     |


In [25]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
slice=a[:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [29]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
a
b=a


In [34]:
b[0]=99

In [35]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [36]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# MATRIX OPERATIONS

In [41]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [42]:
A

array([[1, 2],
       [3, 4]])

## Matrix multiplications
![image](https://www.geeksforgeeks.org/matrix-multiplication/)

✅ 2. Matrix Multiplication (@ or np.dot())
Follows the rules of linear algebra:

If A is (m x n), and B is (n x p), result is (m x p)

 Method 1: Using @ operator

C = A @ B


Method 2: Using np.dot()

C = np.dot(A, B)


✅ 3. np.matmul() — Also for Higher Dimensions

C = np.matmul(A, B)
Same result as np.dot() for 2D, but better for 3D tensors.


| Operation             | Symbol / Function              | Use Case                   |
| --------------------- | ------------------------------ | -------------------------- |
| Element-wise          | `*`                            | Same shape arrays          |
| Matrix multiplication | `@`, `np.dot()`, `np.matmul()` | Linear algebra (row × col) |


❗ Common Error:
Shapes must align:
If A is (2x3), B must be (3xN) for matrix multiplication.

In [43]:
A@B

array([[19, 22],
       [43, 50]])

In [44]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

## Transpose of matrix

✅ What is Transpose?
Transpose means flipping rows into columns (and vice versa).

If:

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])


Then
A.T
[[1 3 5]
 [2 4 6]]



**🔹 Syntax:**


A.T               # Shortcut way
np.transpose(A)   # Full method


🧠 Works With:


| Type     | Transpose Result |
| -------- | ---------------- |
| 1D Array | No change        |
| 2D Array | Rows ↔ Columns   |
| 3D+      | Axes get swapped |


In [45]:
A.T

array([[1, 3],
       [2, 4]])

In [46]:
np.transpose(B)

array([[5, 7],
       [6, 8]])

# Advanced Array Manipulations

## Stacking Array

Stacking means joining multiple arrays into a single array — either vertically, horizontally, or depth-wise

| Function             | Axis | Description           |
| -------------------- | ---- | --------------------- |
| `vstack()`           | 0    | Stack row-wise        |
| `hstack()`           | 1    | Stack column-wise     |
| `dstack()`           | 2    | Stack depth-wise (3D) |
| `stack(..., axis=n)` | n    | Stack on any axis     |


In [51]:
x= np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [52]:
np.vstack((x,y))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
np.hstack((x,y))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
np.column_stack((x,y))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

## Splitting array

Splitting means dividing one array into multiple sub-arrays.

🧠 Notes:
split() requires even division or it throws an error.

array_split() is the safest for dynamic splits.

For 2D arrays:

vsplit() = splits rows.

hsplit() = splits columns.

dsplit() works only on 3D arrays and splits along depth.



| Function           | Purpose                | Works On | Axis Split Along                | Equal Parts Only? | Allows Uneven Split? | Example (Shape)                       |
| ------------------ | ---------------------- | -------- | ------------------------------- | ----------------- | -------------------- | ------------------------------------- |
| `np.split()`       | Split into equal parts | 1D, 2D   | Axis `0` (default) or specified | ✅ Yes             | ❌ No                 | `np.split(arr, 3)` → 3 equal chunks   |
| `np.array_split()` | Split into any parts   | 1D, 2D   | Axis `0` (default) or specified | ❌ No              | ✅ Yes                | `np.array_split(arr, 4)` → any sizes  |
| `np.hsplit()`      | Split **columns**      | 2D       | Axis `1` (horizontal)           | ✅ Yes             | ❌ No                 | `np.hsplit(arr, 2)` → 2 col blocks    |
| `np.vsplit()`      | Split **rows**         | 2D       | Axis `0` (vertical)             | ✅ Yes             | ❌ No                 | `np.vsplit(arr, 2)` → 2 row blocks    |
| `np.dsplit()`      | Split **depth** (3D)   | 3D       | Axis `2` (depth-wise)           | ✅ Yes             | ❌ No                 | `np.dsplit(arr, 2)` → 3D depth slices |


In [56]:
z=np.arange(16).reshape(4,4)
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
np.hsplit(z,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [58]:
np.vsplit(z,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]