In [1]:
import numpy as np

### Now the NumPy package can be referred to as np instead of numpy.

Basic array Creations

To Create a array use function np.array([])

In [17]:
arr=np.array([1,2,3,4,5])
arr




array([1, 2, 3, 4, 5])

To print directly use variable in which array is stored as arr

**Creating A 2D matrix**

In [18]:
l=([1,2,3],[4,5,6],[8,9,7])
l

([1, 2, 3], [4, 5, 6], [8, 9, 7])

# Now when we will convert it into array it will gives in 2d matrix 

In [19]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 7]])

*Above 2D that is like 3D,4D .... we call it as tensoe

#Array generation Functions

In [22]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

To create in form of matrix write in double ((row,columns)) ex; below

In [25]:
arr=np.zeros((3,4))
arr


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#np.linspace() returns evenly spaced values between a start and stop value.
📌 Use Cases:
Creating smooth ranges of numbers

Useful in graph plotting

Great for sampling data points

In [26]:
arr=np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [27]:
arr=np.linspace(0,1,50)
arr

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

**Random Generations Functions**
# NumPy offers the random module to work with random numbers.

# Generate Random Float
The random module's rand() method returns a random float between 0 and 1.

In [28]:
np.random.rand(10)

array([0.0145531 , 0.70362804, 0.06624684, 0.87218359, 0.84121195,
       0.44532867, 0.94526947, 0.0769856 , 0.96163135, 0.43454346])

In [29]:
np.random.randn(10)

array([ 0.29937578,  0.8830799 , -0.71749997, -0.15758199,  0.31175493,
        0.28327901, -0.88957029, -0.78601197, -0.94593663, -0.49293129])

In [30]:
np.random.rand(10)

array([0.07521374, 0.41404774, 0.86691148, 0.51810421, 0.03792595,
       0.18826058, 0.3450155 , 0.03458367, 0.3376306 , 0.39273524])

In [33]:
np.random.randint(10,20,10)

array([13, 18, 15, 15, 11, 18, 18, 11, 12, 11])

**Array Attributes**

In [37]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr.shape

(3, 3)

In [39]:
arr.size

9

In [40]:
arr.dtype

dtype('int32')

**Array Methods**

In [41]:
arr.min()


1

In [42]:
arr.max()

9

In [43]:
arr.sum()


45

**arr.sum() → Sum of all values**

**axis=0 → Column-wise sum**

**axis=1 → Row-wise sum**

In [44]:
arr.sum(axis=0)

array([12, 15, 18])

In [45]:
arr.sum(axis=1)

array([ 6, 15, 24])

📊 arr.mean() in NumPy
✅ Purpose:
Calculates the average (mean) of all elements in the array.

arr.mean() → Mean of all elements

axis=0 → Column-wise average

axis=1 → Row-wise average


In [46]:
arr.mean()

5.0

In [47]:
arr.mean(axis=0)

array([4., 5., 6.])

In [48]:
arr.mean(axis=1)

array([2., 5., 8.])

📉 arr.std() in NumPy
✅ Purpose:
Calculates the standard deviation of all elements in the array — a measure of how spread out the values are.
arr.std() → Standard deviation of all elements

axis=0 → Column-wise spread

axis=1 → Row-wise spread

In [49]:
arr.std()

2.581988897471611

In [50]:
arr.std(axis=1)


array([0.81649658, 0.81649658, 0.81649658])

In [51]:
arr.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

🏆 arr.argmax() in NumPy
✅ Purpose:
Returns the index of the maximum value in the array (as if it's flattened).
arr.argmax() → Index of global max (flattened)

axis=0 → Index of max in columns

axis=1 → Index of max in rows

In [52]:
arr.argmax()

8

In [54]:
arr.argmax(axis=0)


array([2, 2, 2], dtype=int64)

🔽 arr.argmin() in NumPy
✅ Purpose:
Returns the index of the smallest value in the array (as if it's flattened).
arr.argmin() → Index of min in entire array (flattened)

axis=0 → Column-wise min index

axis=1 → Row-wise min index

In [56]:
arr.argmin()

0

**Reshaping And Resizing**

In [58]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

🔄 arr.reshape() in NumPy
✅ Purpose:
Changes the shape/dimensions of the array without changing data.

⚠️ Note:
The product of new shape must equal the number of elements
E.g. 6 elements → reshape(2,3) is OK
❌ reshape(2,4) → Error

📌 Summary:
Use reshape() to convert 1D → 2D, 2D → 3D, etc.

Helps in matrix operations, ML, image processing

In [ ]:
arr.reshape